### ISSUE TITLE
Blocked channels show up when browsing communities.

### ISSUE THREAD

**Issue by Anipsy** [LinogeFly/hide-unwanted-streams-on-twitch#14]
Hey, so recently Twitch added communities(beta), and blocked channels show up in there, just a little annoyance, but still, imo that should not happen.

**Comment by LinogeFly** [comment]
Hi! Thanks for letting me know about this. I will look into it soon.

**Comment by LinogeFly** [comment]
Communities pages are supported now. Wait until the extension is updated in Chrome or update it manually to get the latest version.
