### ISSUE TITLE
Extension/Userscript not working in https://www.twitch.tv/directory/all

### ISSUE THREAD

**Issue by oakenhold** [LinogeFly/hide-unwanted-streams-on-twitch#17]
I have tried both the userscript and extension, I am unable to see the "Block | Settings" overlay when browsing https://www.twitch.tv/directory/all or https://www.twitch.tv/directory/all/zh.

The overlay still appears when I am browsing by game.

**Comment by LinogeFly** [comment]
Hi! Thanks for letting me know. Yes, looks like overlay on game pages stopped working after recent update on Twitch. I will look into it soon and fix.

**Comment by LinogeFly** [comment]
It should be work again now.

**Comment by LinogeFly** [comment]
Thanks for reporting this issue. I will fix it soon.

**Comment by LinogeFly** [comment]
Should work again. Please, get the latest version.

**Comment by oakenhold** [comment]
Yup, working now, thanks!
