### ISSUE TITLE
Blocking games not working

### ISSUE THREAD

**Issue by mbtestgem** [LinogeFly/hide-unwanted-streams-on-twitch#2]
Version 40.0.2214.111 m

Mousing over the games does not provide the block | settings options that mousing over the channels does.

**Comment by LinogeFly** [comment]
Hi mbtestgem,
Are you trying to get "block | settings" menu on [Games](http://www.twitch.tv/director) page? Because overlay menu for blocking games is only available on that page where games are listed with big images.

**Comment by LinogeFly** [comment]
See screenshot below for demonstration of what I mean:

![image](https://cloud.githubusercontent.com/assets/10357631/6118216/13ffd39a-b0c4-11e4-8ef3-a8bd828803b5.png)

**Comment by mbtestgem** [comment]
Ah. My bad. I was trying it on the front page.

Thanks.
