### ISSUE TITLE
GM is not defined (on FF Quantum)

### ISSUE THREAD

**Issue by jpsouzasilva** [LinogeFly/hide-unwanted-streams-on-twitch#21]
![bug](https://i.imgur.com/5PDLX1m.png)

**Version:** 1.3.26.
**Browser:** FF Quantum 57 (64-bit).
**OS:** Windows 10.

None of the previous versions worked either.

**Comment by LinogeFly** [comment]
Hi! Really? Wow, my last update was supposed to fix that actually :). And one guy, who reported that issue, said that it got fixed and the update. Weird. Thanks for information, I will look into it soon.

**Comment by LinogeFly** [comment]
What version of Greasemonkey do you have installed?

**Comment by LinogeFly** [comment]
If you don't have Greasemonkey 4 or higher, then please update it.

**Comment by jpsouzasilva** [comment]
hey @LinogeFly sorry for the late reply!

I was using ViolentMonkey, actually. The add-on information page said GM functions were supported, but I guess the extension is bugged.

**Switching to Greasemonkey fixed my problem. Thanks!**
