### ISSUE TITLE
Kinda broken Apr 2018

### ISSUE THREAD

**Issue by atshum** [LinogeFly/hide-unwanted-streams-on-twitch#24]
When I first go to a channel listing (https://www.twitch.tv/directory/all) the extension does not work -- I see channels that should be hidden, and I do not see the "Block | Settings" menu when hovering over a channel.

When I scroll down so that the browser fetches more results from Twitch, the extension works on the previously loaded results -- the channels that should be hidden are hidden, and the menu works.  However, it does not work on the newly loaded results.

This behavior started a couple days ago.  I am using Chrome on Windows 7 and 10.

**Comment by LinogeFly** [comment]
I just deployed a new version with a fix for this issue to Chrome Store. Should be working fine now.
