### ISSUE TITLE
Block lists get erased after QUOTA_BYTES limit

### ISSUE THREAD

**Issue by LinogeFly** [LinogeFly/hide-unwanted-streams-on-twitch#5]
When blocking new streams/games fails because of hitting QUOTA_BYTES limit block list for streams/games gets erased.

**Comment by artemyarulin** [comment]
![wow](https://i.imgflip.com/7cv7t.jpg)

**Comment by mrjnumber1** [comment]
wait, does this also apply to the tampermonkey script ?

**Comment by LinogeFly** [comment]
No, this bug was related specifically to Chrome Extension implementation. Tampermonkey version didn't have such problem.
