### ISSUE TITLE
#6 returned

### ISSUE THREAD

**Issue by MadMakz** [LinogeFly/hide-unwanted-streams-on-twitch#7]
Bug #6 is back. See my comment over there.

**Comment by LinogeFly** [comment]
Hi MadMakz,
This bug should be gone now in the latest version.

**Comment by LinogeFly** [comment]
Let me know if it got fixed for you once you have got a latest version.

**Comment by MadMakz** [comment]
Looking good :+1:

**Comment by LinogeFly** [comment]
Great! :)
